export interface ContactMessage {
    
    contactMessageId?: number;            // Optional: will be auto-generated by backend
    name: string;
    email: string;
    subject: string;
    message: string;
    createdAt?: string;     // Optional: set by backend
}